language: ruby
rvm:
  - 2.1.8
  - 2.2.0
  - 2.3.1
script:
  - bundle exec rspec
env:
  - COVERAGE=true
script:
  - bundle exec rspec
branches:
  only:
    - master
sudo: false
notifications:
  - email: false
