language: ruby
rvm:
  - 2.1.8
  - 2.2.0
  - 2.3.0
env:
  - COVERAGE=true
before_install:
  - git clone https://github.com/danascheider/raml-rb
  - gem build raml-rb/raml-rb.gemspec
  - gem install raml-rb-0.0.5.gem
branches:
  only:
    - dev
    - staging
    - master
sudo: false
notifications:
  - email: false
